config/routes.rb
Rails.application.routes.draw do
  resources :companies, only: %i[new edit create update]
  resources :positions, only: %i[index new edit show create update]
  resources :applicants, only: %i[index new create]
  devise_for :users
  root 'home#index'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :positions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :bigint           not null, primary key
#  name       :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_companies_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Company < ApplicationRecord
  belongs_to :user
  has_one_attached :logo

  validates :name, :url, presence: true
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :bigint           not null, primary key
#  carrer      :integer
#  city        :string
#  contract    :integer
#  description :text
#  name        :string
#  publish     :boolean
#  remote      :boolean
#  state       :string
#  summary     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  company_id  :bigint           not null
#
# Indexes
#
#  index_positions_on_company_id  (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (company_id => companies.id)
#
class Position < ApplicationRecord
  belongs_to :company
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :company
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def new
    @company = current_user.build_company
  end

  def edit
    @company = current_user.company
  end

  def create
    @company = current_user.build_company(company_params)

    if @company.save
      flash[:notice] = 'Company created successfully'
      redirect_to root_path
    else
      flash[:error] = 'Company not created'
      render :new
    end
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = 'Company updated successfully'
      redirect_to root_path
    else
      flash[:error] = 'Company not updated'
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/applicants/index.html.erb
<h1>Applicants#index</h1>
<p>Find me in app/views/applicants/index.html.erb</p>

app/views/applicants/new.html.erb
<h1>Applicants#new</h1>
<p>Find me in app/views/applicants/new.html.erb</p>

app/views/base/_control_sidebar.html.erb
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

app/views/base/_footer.html.erb
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

app/views/base/_header.html.erb
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
   <div class="container">
      <%= link_to root_path, class: 'navbar-brand' do %>
         <span class="brand-text font-weight-light">DEV_JOB/HUB</span>
      <% end %>
      <button class="navbar-toggler order-1 collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse order-3 collapse" id="navbarCollapse" style="">
         <ul class="navbar-nav">
            <li class="nav-item">
               <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
               <%= link_to 'New Company', new_company_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
               <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Dropdown</a>
               <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                  <li><a href="#" class="dropdown-item">Some action </a></li>
                  <li><a href="#" class="dropdown-item">Some other action</a></li>
               </ul>
            </li>
         </ul>
      </div>
      <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
         <% if user_signed_in? %>
            <li class="nav-item">
               <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
         <% else %>
            <li class="nav-item dropdown">
               <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item dropdown">
               <%= link_to 'Cadastro', new_user_registration_path, class: 'nav-link' %>
            </li>
         <% end %>
      </ul>
   </div>
</nav>

app/views/base/_sidebar.html.erb
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="/assets/adminlte/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/assets/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Starter Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Active Page</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Inactive Page</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Simple Link
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/companies/_form.html.erb
<div class="row">
   <div class="col-md-12">
      <div class="card card-primary">
         <div class="card-header">
            <h3 class="card-title">Cadastre sua empresa</h3>
            <div class="card-tools">
               <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
               <i class="fas fa-minus"></i>
               </button>
            </div>
         </div>

         <%= simple_form_for @company, data: { turbo: false }  do |f| %>
            <%= f.error_notification %>
            <div class="card-body" style="display: block;">
               <div class="form-group">
                  <%= f.input :name, class: "form-control" %>
               </div>
               <div class="form-group">
                  <%= f.input :url, class: "form-control" %>
               </div>
               <div class="form-group">
                  <%= f.input :logo, class: "form-control" %>
               </div>
            </div>
            <div class="card-footer">
               <%= f.button :submit, class: "btn btn-primary" %>
            </div>
         <% end %>
      </div>
   </div>
</div>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/new.html.erb
<%= render partial: 'shared/content_header', locals: { page_title: "Cadastrar empresa" } %>

<%= render "form" %>

app/views/home/index.html.erb
teste

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/assets/adminlte/dist/css/adminlte.min.css?v=3.2.0">
    <link rel="stylesheet" href="/assets/adminlte/plugins/fontawesome-free/css/all.min.css"/>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

<body class="hold-transition layout-top-nav">
   <div class="wrapper">
        <%= render "base/header" %>

         <div class="content-wrapper">
          <div class="content container-fluid">
            <div class="container-fluid">
              <div class="container pt-2">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
        <%= render "base/footer" %>
      <div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>App</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
   </head>
   <body data-scrollbar-auto-hide="n" class="hold-transition sidebar-mini layout-fixed">
        <div class="hold-transition login-page">
            <div class="container-fluid">
                <main class="hold-transition login-page">
                    <%= yield %>
                </main>
            </div>
        </div>
   </body>
</html>

app/views/positions/edit.html.erb
<h1>Positions#edit</h1>
<p>Find me in app/views/positions/edit.html.erb</p>

app/views/positions/index.html.erb
<h1>Positions#index</h1>
<p>Find me in app/views/positions/index.html.erb</p>

app/views/positions/new.html.erb
<h1>Positions#new</h1>
<p>Find me in app/views/positions/new.html.erb</p>

app/views/positions/show.html.erb
<h1>Positions#show</h1>
<p>Find me in app/views/positions/show.html.erb</p>

app/views/shared/_content_header.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1><%= page_title %></h1>
      </div>
    </div>
  </div>
</section>